#!/usr/bin/env python3
"""
gen_gemm_top.py - Generate complete gemm_top instantiation
Extracts ports from all sub-modules and produces gemm_top_internal.sv snippet.
"""
import sys, re, os, glob

RTL_DIR = '/root/.openclaw/workspace/GEMM/rtl'

# Order of instantiation
MODULES = [
    'err_checker', 'perf_counter', 'trace_debug_if',
    'axi_rd_master', 'axi_wr_master',
    'dma_rd', 'dma_wr',
    'buffer_bank',
    'a_loader', 'b_loader', 'c_loader', 'd_storer',
    'array_io_adapter', 'systolic_core', 'postproc',
]

def extract_ports(path):
    with open(path) as f:
        text = f.read()
    # Find between module ... ( and );
    m = re.search(r'module\s+\w+\s*#?\s*\([^\)]*\)\s*\((.*?)\);', text, re.DOTALL)
    if not m:
        return []
    body = m.group(1)
    ports = []
    # Simple line-by-line parser
    for raw_line in body.split('\n'):
        line = raw_line.strip().rstrip(',')
        if not line or line.startswith('//') or line.startswith('/*') or line.startswith('*'):
            continue
        # direction width? name
        mm = re.match(r'(input|output)\s+(?:reg\s+)?(?:wire\s+)?((?:\[.*?\])?)\s*([A-Za-z_][A-Za-z0-9_]*)', line)
        if mm:
            dir_, width, name = mm.groups()
            ports.append((dir_, width.strip(), name))
        else:
            # Maybe width on next line? skip for now
            pass
    return ports

def main():
    print("// Auto-generated internal wires and instantiations for gemm_top")
    print("// Generated by gen_gemm_top.py")
    print()
    # Wire declarations
    all_wires = set()
    for mod in MODULES:
        path = os.path.join(RTL_DIR, f'{mod}.sv')
        ports = extract_ports(path)
        for dir_, width, name in ports:
            if name in ('clk', 'rst_n'):
                continue
            key = (width, name)
            if key not in all_wires:
                all_wires.add(key)
                wdecl = f"wire {width} {name};" if width else f"wire {name};"
                print(f"    {wdecl}")
    print()
    # Instantiations
    for mod in MODULES:
        path = os.path.join(RTL_DIR, f'{mod}.sv')
        ports = extract_ports(path)
        print(f"    // {mod}")
        print(f"    {mod} #(./*TODO parameters*/) u_{mod} (")
        conn = []
        for dir_, width, name in ports:
            if name in ('clk', 'rst_n'):
                conn.append(f"        .{name}({name})")
            else:
                conn.append(f"        .{name}({name})")
        print(",\n".join(conn))
        print(f"    );")
        print()

if __name__ == '__main__':
    main()
